# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   annotations:
#     configmap.reloader.stakater.com/reload: test-configmap
#   labels:
#     app: test
#   name: test 
#   namespace: $NAMESPACE
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: test
#   template:
#     metadata:
#       labels:
#         app: test
#     spec:
#       containers:
#         image: dockerregistry.io/test:$TAG
#         imagePullPolicy: Always
#         name: test
#         ports:
#         - containerPort: 5000
#           protocol: TCP
#         volumeMounts:
#         - mountPath: /app/settings.json
#           name: test-volume
#           subPath: settings.json
#       restartPolicy: Always
#       volumes:
#       - configMap:
#           defaultMode: 420
#           name: test-configmap
#         name: test-volume

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: app
          image: dockerregistry.io/test:$TAG
          env:
            - name: CUSTOM_ENV_VARIABLE
              value: some-value