
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: app
          image: dockerregistry.io/test:$TAG
          env:
            - name: CUSTOM_ENV_VARIABLE
              value: some-value
